env:
  CGO_ENABLED: 0
  GOOS: linux
  BUILD: 1.0
  IMG_LINUX_ARM: xfer-linux-arm64
  IMG_LINUX: xfer-linux-amd64
  IMG_MAC: xfer-mac-arm64
  IMG_MAC_AMD: xfer-mac-amd64
  IMG_WINDOWS: xfer-win-amd64.exe

functions:

  - name: release
    description: build all releases for production
    run:
      - bash -c ./next-version.sh
      - $(build-linux-arm)
      - $(build-linux)
      - $(build-mac)
      - $(build-mac-amd)
      - $(build-windows)
      - gh release create --generate-notes -t "${BUILD}.$(( cat version ))" ${BUILD}.$(( cat version )) 'bin/${IMG_LINUX}' 'bin/${IMG_LINUX_ARM}' 'bin/${IMG_MAC}' 'bin/${IMG_MAC_AMD}' 'bin/${IMG_WINDOWS}'

  - name: build-linux
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - go build -ldflags="-X 'main.Version=${BUILD}.$((cat version))'" -o bin/${IMG_LINUX}

  - name: build-linux-arm
    env:
      GOOS: linux
      GOARCH: arm64
    run:
      - go build -ldflags="-X 'main.Version=${BUILD}.$((cat version))'" -o bin/${IMG_LINUX_ARM}

  - name: build-mac
    env:
      GOOS: darwin
      GOARCH: arm64
    run:
      - go build -ldflags="-X 'main.Version=${BUILD}.$((cat version))'" -o bin/${IMG_MAC}

  - name: build-mac-amd
    env:
      GOOS: darwin
      GOARCH: amd64
    run:
      - go build -ldflags="-X 'main.Version=${BUILD}.$((cat version))'" -o bin/${IMG_MAC_AMD}

  - name: build-windows
    env:
      GOOS: windows
      GOARCH: amd64
    run:
      - go build -ldflags="-X 'main.Version=${BUILD}.$((cat version))'" -o bin/${IMG_WINDOWS}
